### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by smremde** [28msec/gridfs-fuse#1]
I tried to compile on 14.04 after modifying the code to work with the latest mongodb drivers but I have this error when linking:

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libmongoclient.a(spin_lock.o): undefined reference to symbol 'pthread_yield@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

If I add -lpthread to the command, I get a lot of errors with undefined references to boost.
I'm not sure if I have set up my environment wrong (most likely) but I was wondering what the status of this project is and if there is any chance of getting an update for 14.04?

**Comment by tmbdev** [comment]
The code isn't working with current versions of MongoDB; for example, 

mongo/client/dbclient.h

doesn't exist anymore. The new include path is:

mongo-client/mongo-client.h
